### ISSUE TITLE
Ordering Issue and Infinite Loop

### ISSUE THREAD

**Issue by haydennix55** [ceilingcranes/Hartnett_CSCI2270_FinalProject#2]
While entering many patients, I noticed they did not store to the array in urgency order, which I assumed was by design.  When I went to "Get patient" however, It would give the first patient entered and from then it would go in Priority order.  for example, if i entered a patient with urgency 1, then another with 5, then another with 10, it would get 1, then 10, then 5.  

While investigating this once, I got an infinite loop saying "One or more....swapped"

Not sure how to fix

**Comment by ceilingcranes** [comment]
I believe I fixed the problem- it was a stray else statement from when I was testing. Thank you so much for bringing this to my attention!
